= REST API Level 0 - Node.js Example Application

IMPORTANT: This example application requires Node.js 8.x or greater and `npm` 5 or greater.



== Running the Example Application Locally

To run this example application on your local host:

[source,bash,options="nowrap",subs="attributes+"]
----
$ unzip spiffy-cactus.zip

$ cd spiffy-cactus

$ npm install && npm start
----

== Interacting with the Example Application Locally

To interact with your example application while it's running locally, use the form at `http://localhost:8080` or the `curl` command:

[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://localhost:8080/api/greeting
{"content":"Hello, World!"}

$ curl http://localhost:8080/api/greeting?name=Sarah
{"content":"Hello, Sarah!"}
----


== Updating the Example Application
To update your example application:

. Stop your example application.
+
NOTE: To stop your running example application in a Linux or macOS terminal, use `CTRL+C`. In a Windows command prompt, you can use `CTRL + Break(pause)`.

. Make your change (e.g. edit `public/index.html`).
. Restart your example application.
. Verify the change took effect.


== Running the Example Application on a Single-node OpenShift Cluster
If you have a single-node OpenShift cluster, such as Minishift or Red Hat Container Development Kit, installed and running, you can also deploy your example application there. A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your example application to a running single-node OpenShift cluster:
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer

$ oc new-project MY_PROJECT_NAME

$ npm install && npm run openshift
----

== More Information
You can learn more about this example application and rest of the Node.js runtime in the link:https://access.redhat.com/documentation/en-us/red_hat_build_of_node.js/[Node.js Runtime Guide].


