// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@v0.20.0',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowMinimal(
    stepRunnerConfigDir: 'cicd/ploigos-integration-environment/jenkins/minimal/ploigos-step-runner-config/',

    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-nodejs-npm-jenkins-min-hello',
    workflowServiceAccountName: 'ploigos-workflow-ref-nodejs-npm-jenkins-min-hello',

    workflowWorkerImageDefault: 'ploigos/ploigos-base:v0.22.0',
    workflowWorkerImageAgent: 'ploigos/ploigos-ci-agent-jenkins:v0.22.0',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-javascript:v0.22.0',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-containers:v0.22.0',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:v0.22.0',

    stepRunnerUpdateLibrary: 'true',
    stepRunnerLibSourceUrl: 'git+https://github.com/ploigos/ploigos-step-runner.git@main',

    verbose: 'true'
)
